### ISSUE TITLE
Swagger Ui is loading after upgrading version 1.3.1 release

### ISSUE THREAD

**Issue by sanjeevdevaraj** [swaggo/echo-swagger#83]
We are getting below error when we load swagger ui. 

reactProdInvariant.js:29 Uncaught Invariant Violation: Minified React error #37; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=37 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at e.exports (https://sunpathms.cmh.reportsstage.evinternal.net/swagger/swagger-ui-bundle.js:2:77966)
    at Object._renderNewRootComponent (https://sunpathms.cmh.reportsstage.evinternal.net/swagger/swagger-ui-bundle.js:2:628862)
    at Object._renderSubtreeIntoContainer (https://sunpathms.cmh.reportsstage.evinternal.net/swagger/swagger-ui-bundle.js:2:629937)
    at Object.render (https://sunpathms.cmh.reportsstage.evinternal.net/swagger/swagger-ui-bundle.js:2:630064)
    at j (https://sunpathms.cmh.reportsstage.evinternal.net/swagger/swagger-ui-bundle.js:2:274191)
    at m (https://sunpathms.cmh.reportsstage.evinternal.net/swagger/swagger-ui-bundle.js:2:1089719)
    at Lr (https://sunpathms.cmh.reportsstage.evinternal.net/swagger/swagger-ui-bundle.js:2:1090084)
    at window.onload (https://sunpathms.cmh.reportsstage.evinternal.net/swagger/index.html:75:14)

**Comment by ubogdan** [comment]
Not sure about this. Can you paste  your echo-swagger setup please.

**Comment by ubogdan** [comment]
Please test with 1.3.2

**Comment by sanjeevdevaraj** [comment]
Thank you its working good now
